

INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (1, 'TONY STARK');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (2, 'STEVIE ROGERS');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (3, 'NATASHA ROMANOFF');

INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (1, 'SMART TV');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (2, 'MACBOOK AIR PRO 15');

INSERT INTO TB_WISH_LIST (CLIENT_ID, PRODUCT_ID) VALUES (1, 1);

