-- Initial data load

INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (1, 'TONY STARK');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (2, 'STEVE ROGERS');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (3, 'NATASHA ROMANOFF');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (4, 'CLARK KENT');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (5, 'BRUCE WAYNE');
INSERT INTO TB_CLIENT (CLIENT_ID, NAME) VALUES (6, 'DIANA PRINCE');

INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (1, 'Smart TV 86" 4K LG 86QNED80SRA Quantum Dot NanoCell 120Hz FreeSync ThinQ AI Alexa Google 4HDMI');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (2, 'Apple notebook MacBook Pro (de 16 polegadas, Processador M1 Pro da Apple com CPU 10‑core e GPU 16‑core, 16 GB RAM, 512 GB SSD)');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (3, 'Acer Notebook Gamer Nitro 5');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (4, 'Samsung Galaxy S23 Ultra 5G 512GB');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (5, 'Apple iPhone 14 Pro (512 GB) – Roxo-profundo');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (6, 'Xiaomi 13 PRO 12+512,Preto');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (7, 'Smart TV QLED 85" 4K UHD Samsung Q70C');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (8, 'Samsung Smart TV 85" Neo QLED 4K 85QN85C 2023');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (9, 'Par de Caixas Acústicas Torre Yamaha Preta NS-F51 240W 3 Alto Falantes com 2 woofers de 16cm');
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME) VALUES (10, 'Jbl Stage A130 - Par de caixas acústicas Bookshelf para Home Theater');

INSERT INTO TB_WISH_LIST (CLIENT_ID, PRODUCT_ID) VALUES (1, 1);
INSERT INTO TB_WISH_LIST (CLIENT_ID, PRODUCT_ID) VALUES (1, 2);
INSERT INTO TB_WISH_LIST (CLIENT_ID, PRODUCT_ID) VALUES (1, 9);

